---
- hosts: localhost
  connection: local
  vars_files:
    - vars.yml

  #debugger: on_failed

  tasks:

  - name: Distribution
    debug: msg="{{ ansible_distribution }}"

  - name: Distribution
    debug: msg="{{ ansible_distribution_release }}"
