- name: Git zerotier checkout
  git:
    repo: 'https://github.com/zerotier/ZeroTierOne.git'
    dest: /home/{{ user }}/bin/installers/zerotier/

- name: Install dependencies
  zypper:
    name: 
      - make
      - gcc-c++
      - cargo
      - libopenssl-1_1-devel
    state: present

- name: Build the default target
  make:
    chdir: /home/{{ user }}/bin/installers/zerotier/

- name: Run 'install' target as root
  make:
    chdir: /home/{{ user }}/bin/installers/zerotier/
    target: install
  become: yes

#- name: Join zerotier-one network
#  shell: /home/{{ user }}/bin/installers/zerotier/zerotier-one -d
#  become: yes

- name: Copy the zerotier-one service file
  copy:
    src: zerotier-one.service
    dest: /lib/systemd/system/zerotier-one.service