- name: Install docker-compose & docker
  zypper:
    name:
      - python3-docker-compose
    state: present
    update_cache: yes
  become: yes

- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes
  become: yes

- name: Enable service docker
  systemd:
    name: docker
    enabled: yes
  become: yes

- name: Load docker on boot
  systemd:
    state: started
    name: docker
  become: yes