- name: Install git
  package: 
    name: git
    state: present
  become: yes

- name: Set gir config global user email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"

- name: Set gir config global user name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_name }}"