- name: Install virtualbox
  pacman:
    name: 
      - virtualbox
      - virtualbox-host-dkms
    state: present
  become: yes

- name: Install oracle vbox extensions
  yay:
    name: virtualbox-ext-oracle
    state: present
  become: yes
