- name: Add sublime apt-key for KDE Neon
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  become: yes

- name: Add sublime apt repository for Kde neon
  apt_repository:
    repo: 'deb https://download.sublimetext.com/ apt/stable/'
    state: present
    filename: sublime
    update_cache: yes
  become: yes

- name: Update apt repo and cache (sudo apt update)
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes