- name: Import sublime key for Tumbleweed
  rpm_key:
    state: present
    key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
  become: yes

- name: Add sublime repo and add its gpg key for Tumbleweed
  zypper_repository:
    repo: 'https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo'
    runrefresh: true
  become: yes

- name: Update all zypper packages
  zypper:
    name: '*'
    state: dist-upgrade
    update_cache: true
  become: yes
